### PR TITLE
Make the Behat tests a bit faster and more robust

### PR DESCRIPTION
**Pull request by timhunt**
Hi Richard. I hope these are some useful improvements to the Behat tests. I have to admit that I am struggling to run all the tests reliably on my development computer at the moment - which I why I started making these changes to improve things. These changes make things better, any anyway will speed up the test runs a bit. They mostly pass on github actions, except for some which I think were failing anyway.

Tim.

### CODE REVIEW

**Comment by timhunt** [comment]
Well, Behat seems to have passed in the GitHub Actions runs here, so hopefully that is a sign I have not messed it up!

**Comment by trampgeek** [comment]
Many thanks Tim. It all sounds good but I don't have time to play right now. Hope to find time over the weekend. We'll see.

**Comment by trampgeek** [comment]
Many thanks Tim. Lots of great work there. It's nice to have someone who actually *understands* behat tidying things up :)

**Comment by trampgeek** [comment]
The updated code passes all the behat tests on my system. IMany thanks again.

It still fails on a couple of tests in GitHub Actions because I don't seem to have found a general purpose way of dismissing an Alert box. I've spent quite a while playing with this and trying lots of internet purported solution that just don't work for me. It's the function i_set_the_field_and_dismiss_the_alert in behat_coderunner.php. If you know of a solution, that would be great. Otherwise, I'm just accepting that the two tests that work on my system don't work with CI.

**Comment by timhunt** [comment]
I think I have hit issues with that in the past, but I don't remember where I got understanding it. Sorry.

(It may be a thing that works in Firefox but not Chrome, or vice vesa. Generically, the way to work-around this is to add a tag to these tests - e.g. @usesalerts, and then in the behat command-line you add an option to exclude those tests, something like --tags ~usesalerts from memory, but that might not be quite right.)

**Pull request merged**
