### PR TITLE
Fix invalid HTML

### PR DESCRIPTION
**Pull request by timhunt**
Name is not allowed on table elements. As far as I can see, it is not used anywhere, so safe to remove.

### CODE REVIEW

**Comment by timhunt** [comment]
Also, fix inconsistencies between DB structure on install/upgrade.

In case you are interested, I found these by going to Admin -> Development -> XMLDB, and using the various [Check ...] links across the top.

**Comment by trampgeek** [comment]
Thanks for finding the erroneous key and index definitions. I suspect they've been there for many years. Certainly they're in the master branch like that. I guess this just means the keys and index weren't effective. Strange that there is no error messages during install?

However, the "fix inconsistencies" commit isn't good. It is vital that all inherited fields allow null values and that their default values are null. The xmldb tool wanted me to use a default of 0, which I thoughtlessly did, but then broke the entire question database because 0 (or any other non-null value) is taken to mean that the child question is customised, thereby disconnecting it from the parent.

However, I suspect there might be a deeper problem here - why doesn't the xmldb tool allow a null default for a column that can be null? The .xml field definition allows a default of null for a column that can be null, which would seem to be the obvious default. What's going on here?

Richard

**Comment by timhunt** [comment]
Aha! it sort-of makes sense when you think about it. There is no real difference between DEFAULT NULL, and not having a default at all. So, XMLDB wants you to remove the default in that case. I have amended to commit to do that. Hopefully it is OK now.

**Comment by timhunt** [comment]
Third to commit to fix the issue with bulktest URLs you emailed me about.

It definitely works without the require_once for me, but you may have to clear caches.

**Comment by trampgeek** [comment]
Thanks Tim. All merged now.

**Pull request merged**
