### PR TITLE
Minor README fixes

### PR DESCRIPTION
**Pull request by czuhajster**
Hi Richard,

I did a few README fixes. They include: fixing section anchor links, removing duplicated words, and removing a backslash escape inside a span of code.

Best regards,
Arkadiusz

### CODE REVIEW

**Comment by trampgeek** [comment]
Many thanks Arkadiusz - it's great to have to help with the documentation :-)

**Comment by czuhajster** [comment]
Hi Richard,

Thank you for considering my pull request.

Could you please let me know if there was something wrong with the changes that I proposed?

Best regards,
Arkadiusz

**Comment by trampgeek** [comment]
Hi Arkadiusz

**Comment by trampgeek** [comment]
Hi Arkadiusz

There was nothing wrong with them at all! I thought they were great. And I _thought_ I had merged them in before closing. I now see I somehow closed without merging - I must have missed the "Confirm" button. 

Sorry about that. They're now merged. Thanks again (and thanks for drawing to my attention that I hadn't merged).

Richard

**Comment by czuhajster** [comment]
Hi Richard,

No worries :)

Thank you for merging my changes :)

Best regards,
Arkadiusz

**Pull request merged**
