### PR TITLE
Update Behat tests to use the MDL-66821 changes

### PR DESCRIPTION
**Pull request by timhunt**
Hi Richard.

At the point where you start using Moodle 3.8, you will need these changes, or all your Behat tests will start to fail.

And, as soon as you are using 3.7.3 or 3.6.7 for development it will be safe to incorporate these changes.

The explantion is here: https://github.com/moodle/moodle/blob/e04a73ccc06e18d8d3b3661f8f9bc16911747830/question/type/upgrade.txt#L5. I am afraid it is all my fault, but a necessary evil.

### CODE REVIEW

**Comment by timhunt** [comment]
Sorry. I just realised that I have not actually run the edited tests to verify that they pass. Sorry, I was trying to do too many things at the same time. You probably should not merge until I verify that I have run the tests, or you run them yourself.

However, I am about to leave work for the weenend so that won't be until Monday.

**Comment by timhunt** [comment]
Right, I have now run all the Behat tests, and they are all passing, except for question/type/coderunner/tests/behat/check_twig_student_variable.feature, which is failing for me for reasons which I think are not related to my changes.

(I am getting
element not interactable
  (Session info: chrome=77.0.3865.120)
  (Driver info: chromedriver=76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}),platform=Windows NT 10.0.16299 x86_64)
)

Is that test passing for you at the moment?

Apart from that, I think this pull request is now ready to merge.

**Comment by trampgeek** [comment]
Hi Tim

Thanks again.

That test seems to be working for me:

rjl83@rjl83-eb:/var/www/html/moodle$ php admin/tool/behat/cli/run.php /var/www/html/moodle/question/type/coderunner/tests/behat/check_twig_student_variable.feature
Running single behat site:
Moodle 3.7.2+ (Build: 20191031), 711d1a4e7d8ffe3dd7c616f3c567b7fb92fd9bd3
Php: 7.2.24.0.0.18.04.1, mysqli: 5.7.27-0ubuntu0.18.04.1, OS: Linux 4.15.0-66-generic x86_64
Server OS "Linux", Browser: "chrome"
Browser specific fixes have been applied. See http://docs.moodle.org/dev/Acceptance_testing#Browser_specific_fixes
Started at 05-11-2019, 15:06
..............

1 scenario (1 passed)
14 steps (14 passed)
0m58.31s (57.36Mb)
rjl83@rjl83-eb:/var/www/html/moodle$

I do have a weird unrelated problem where a couple of behat tests always 
fail when I run the complete test suite but always work fine when I 
re-run just the failed tests. Did that happen to you?

Richard

**Comment by timhunt** [comment]
I think I saw the thing where tests passed separately, but failed when run together. At least what I saw did not make full sense, but I think you have explained the symptoms now. I will investigate some more.

**Comment by timhunt** [comment]
I can confirm that three of the tests break when run with the others, but then pass separately. However, I don't have time to investigate this week.

I am just going to close this pull request and open a new one, since I rebased on latest devel.

**Pull request closed without merging**
