### PR TITLE
Validate on save should defalt to on

### PR DESCRIPTION
**Pull request by timhunt**
Another small change, which I would personally like to see.

I think 'Validate on save' should be on by default.

### CODE REVIEW

**Comment by timhunt** [comment]
Any thoughts on this Richard? Becasue of OU-internal deadlines, it woud be helpful to me if you could decide this within a week or two. Thanks.

**Comment by timhunt** [comment]
I see Richard has added his own version if this to the development branch (https://github.com/trampgeek/moodle-qtype_coderunner/commit/e994e6751863a7ac932afeaf03ab4ef356c79f5d and https://github.com/trampgeek/moodle-qtype_coderunner/commit/5bad194af9d9c365346cfac9b017b2aa1be40db4) so closing this pull request.

**Comment by trampgeek** [comment]
Sorry about the lack of response to your request-for-comment, Tim. I'm afraid I never actually read it until now. I must have assumed it was the same email as the original request-for-change. But as you've noticed, the change is now in the development branch and live on our production server. I'll merge to main and make a new Moodle repo version early next week.

**Comment by timhunt** [comment]
Thanks.

**Pull request closed without merging**
