### PR TITLE
Fix issue/196

### PR DESCRIPTION
**Pull request by chrahe**
I am not very well versed in the AMD ecosystem, so I am not sure how to build the minified versions of the script. If you need me to do that before merging, please let me know what I need to run :)

### CODE REVIEW

**Comment by timhunt** [comment]
See https://moodledev.io/general/development/tools/nodejs for grunt install instructions, then https://moodledev.io/docs/guides/javascript/modules. (Quite easy if everything works smoothly.)

**Comment by chrahe** [comment]
Im sorry, but I'm a bit confused still. I installed grunt as per the instructions but it's referencing a Gruntfile.js and the package.json, neither of which this repo has. I copied the relevant config files from Moodle core but the Grunt task still doesn't see any of the files in the `amd` folder.

Am I expected to clone the entire main Moodle repository and run the script from there? That seems like a very contrived setup just to transpile a single JavaScript file...

**Comment by timhunt** [comment]
Yes. To do development on a Moodle plugin, you really first need to set up an installation of Moodle (See the first step of https://moodle.academy/course/index.php?categoryid=4) then clone this project into the right subfolder of that to work on (so, you would clone CodeRunner as question/type/coderunner folder inside Moodle.

**Comment by chrahe** [comment]
Got it, thanks for taking the time to explain! I'll set that up tomorrow and then amend this PR.

**Comment by chrahe** [comment]
Hi, just wanted to check back in to ask if anything else is missing still? The minified JS and source map are included in the last commit.

**Comment by trampgeek** [comment]
Thanks chrahe - sorry about not merging earlier. I plain forgot.

**Pull request merged**
